# Site
title:              Santiago Hirschmann
bio:                'Hello! I am a Mechanical Engineering student at Northeastern University'
description:        "I love great design"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Comments
# disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
github:             default

#personal
location:           Boston, MA
phone:              508-951-8736
email:              hirschmann.s@northeastern.edu

resume_path:       /assets/resume/blank santiago hirschmann Resume Fall 2020A.pdf
# Other
background_image:   /images/steel1s.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
